export const Palabras = [
    {id: 1, juego: ["DIO","ES","TA"], palabra: 'Estadio', tipo:'sustantivo-masculino', definicion: 'Recinto deportivo de gran tamaño con gradas para los espectadores'},
    {id: 2, juego: ["DA","PAN"],palabra: 'panda', tipo:'sustantivo-femenino',definicion: 'Mamífero que habita en zonas montañosas y boscosas de China'},
    {id: 3, juego: ["CA","ÑA","BA"],palabra: 'cabaña', tipo:'sustantivo-femenino',definicion: 'Casa rústica hecha de troncos y otros materiales sencillos'},
    {id: 4, juego: ["DO","GA","NA"],palabra: 'ganado', tipo:'sustantivo-masculino',definicion: 'Conjunto de animales criados para su explotación'},
    {id: 5, juego: ["AL","CE"],palabra: 'Alce', tipo:'sustantivo-masculino',definicion: 'Mamífero rumiante , parecido al ciervo y con astas en forma de pala'},
    {id: 6, juego: ["TE","RIA","BAC"],palabra: 'bacteria', tipo:'sustantivo-femenino',definicion: 'Microorganismo unicelular que afecta a los seres vivos'},
    // {id: 7, juego: ["MI","OR","NIS","GA","CRO","MO"],palabra: 'microorganismo', tipo:'sustantivo-masculino',definicion: 'Ser vivo animal o vegetal muy pequeño'},
    {id: 7, juego: ["CLA","AN"],palabra: 'ancla', tipo:'sustantivo-femenino',definicion: 'Objeto que ayuda a fijar y detener barcos'},
    {id: 8, juego: ["MI","LLA","SE"],palabra: 'semilla', tipo:'sustantivo-masculino',definicion: 'Forma parte del fruto, y da origen a una planta'},
    {id: 9,juego: ["SA","PA"], palabra: 'pasa', tipo:'sustantivo-femenino',definicion: 'Es una uva seca'},
    {id: 10,juego: ["TA","ME"], palabra: 'meta', tipo:'sustantivo-masculino',definicion: 'Es un objetivo que queremos cumplir'},
    {id: 11,juego: ["NAZ","TE"], palabra: 'tenaz', tipo:'sustantivo-masculino',definicion: 'Persona que pone mucho empeño'},
    {id: 12,juego: ["LE","VE","TA"], palabra: 'veleta', tipo:'sustantivo-femenino',definicion: 'Señalador que indica la dirección dell viento'},
    {id: 13,juego: ["RO","LO"], palabra: 'loro', tipo:'sustantivo-masculino',definicion: 'Ave grande con plumas coloridas'},
    {id: 14,juego: ["GU","LA","NA"], palabra: 'laguna', tipo:'sustantivo-femenino',definicion: 'Gran depósito natural de agua'},
    // {id: 16,juego: ["DIO","ES","TA"], palabra: 'paramédico', tipo:'adjetivo',definicion: 'Que se relaciona con la medicina sin pertenecer propiamente a esta ciencia'},
    // {id: 17,juego: ["DIO","ES","TA"], palabra: 'Fisioterapeuta', tipo:'nombre-común',definicion: 'Una persona que diseña y enseña ejercicios y actividades para personas con discapacidades físicas.'},
    // {id: 18,juego: ["DIO","ES","TA"], palabra: 'Ortopédico', tipo:'adjetivo',definicion: '— Palabra que describe aparatos, procedimientos o cirugía usados para corregir una deformidad o un impedimento físico.'},
    // {id: 19,juego: ["DIO","ES","TA"], palabra: 'arrasar', tipo:'verbo',definicion: 'Arruinar y destruir por completo un territorio, una superficie, un edificio, etc'},
    // {id: 20,juego: ["DIO","ES","TA"], palabra: 'paradigma', tipo:'nombre masculino',definicion: 'Ejemplo o modelo de algo'},
    // {id: 21,juego: ["DIO","ES","TA"], palabra: 'relieve', tipo:'nombre masculino',definicion: 'Parte que sobresale en una superficie plana.'},
]