export const Palabras = [
    {id: 1, palabra: 'Estadio', tipo:'sustantivo-masculino', definicion: 'Recinto deportivo de gran tamaño con gradas para los espectadores'},
    {id: 2, palabra: 'bacteria', tipo:'sustantivo-femenino',definicion: 'Microorganismo unicelular que afecta a los seres vivos'},
    {id: 3, palabra: 'microorganismo', tipo:'sustantivo-masculino',definicion: 'Ser vivo animal o vegetal muy pequeño'},
    {id: 4, palabra: 'cabaña', tipo:'sustantivo-femenino',definicion: 'Casa rústica hecha de troncos y otros materiales sencillos'},
    {id: 5, palabra: 'ganado', tipo:'sustantivo-masculino',definicion: 'Conjunto de animales criados para su explotación'},
    {id: 6, palabra: 'unicelular', tipo:'adjetivo',definicion: 'Que está compuesto por una sola célula'},
    {id: 7, palabra: 'biología', tipo:'sustantivo-femenino',definicion: 'Ciencia que estudia los seres vivos'},
    {id: 8, palabra: 'antibiótico', tipo:'sustantivo-masculino',definicion: 'Sustancia química para combatir infecciones'},
    {id: 9, palabra: 'discurso', tipo:'sustantivo-masculino',definicion: 'exposición, escrita u oral, en la cual se manifiesta una opinión, razonamiento o deseo'},
    {id: 10, palabra: 'Prótesis', tipo:'sustantivo-masculino',definicion: 'Brazo o pierna artificial.'},
    {id: 11, palabra: 'Velcro', tipo:'sustantivo-masculino',definicion: 'Cinta fuerte y peluda que se pega a sí misma'},
    {id: 12, palabra: 'Virus', tipo:'sustantivo-masculino',definicion: ' Microbios más pequeñitos que las bacterias, que causan algunas enfermedades infecciosas'},
    {id: 13, palabra: 'Parálisis', tipo:'sustantivo-femenino',definicion: 'Debilidad de los músculos; incapacidad para mover una parte o todo el cuerpo'},
    {id: 14, palabra: 'Plaguicidas', tipo:'sustantivo-masculino',definicion: 'Sustancias químicas que matan insectos y otras plagas'},
    {id: 15, palabra: 'Paraplejia', tipo:'enfermedad',definicion: 'Parálisis de ambas piernas'},
    {id: 16, palabra: 'paramédico', tipo:'adjetivo',definicion: 'Que se relaciona con la medicina sin pertenecer propiamente a esta ciencia'},
    {id: 17, palabra: 'Fisioterapeuta', tipo:'nombre-común',definicion: 'Una persona que diseña y enseña ejercicios y actividades para personas con discapacidades físicas.'},
    {id: 18, palabra: 'Ortopédico', tipo:'adjetivo',definicion: '— Palabra que describe aparatos, procedimientos o cirugía usados para corregir una deformidad o un impedimento físico.'},
    {id: 19, palabra: 'arrasar', tipo:'verbo',definicion: 'Arruinar y destruir por completo un territorio, una superficie, un edificio, etc'},
    {id: 20, palabra: 'paradigma', tipo:'nombre masculino',definicion: 'Ejemplo o modelo de algo'},
    {id: 21, palabra: 'relieve', tipo:'nombre masculino',definicion: 'Parte que sobresale en una superficie plana.'},
]