export const Palabras = [
    {id: 1, juego: ["DIO","ES","TA"], palabra: 'Estadio', tipo:'sustantivo-masculino', definicion: 'Recinto deportivo de gran tamaño con gradas para los espectadores'},
    {id: 2, juego: ["PAN","DA"],palabra: 'panda', tipo:'sustantivo-femenino',definicion: 'Mamífero que habita en zonas montañosas y boscosas de China'},
    {id: 3, juego: ["CA","ÑA","BA"],palabra: 'cabaña', tipo:'sustantivo-femenino',definicion: 'Casa rústica hecha de troncos y otros materiales sencillos'},
    {id: 4, juego: ["DO","GA","NA"],palabra: 'ganado', tipo:'sustantivo-masculino',definicion: 'Conjunto de animales criados para su explotación'},
    {id: 5, juego: ["AL","CE"],palabra: 'Alce', tipo:'sustantivo-masculino',definicion: 'Mamífero rumiante , parecido al ciervo y con astas en forma de pala'},
    {id: 6, juego: ["TE","RIA","BAC"],palabra: 'bacteria', tipo:'sustantivo-femenino',definicion: 'Microorganismo unicelular que afecta a los seres vivos'},
    // {id: 3, juego: ["MI","OR","NIS","GA","CRO","MO"],palabra: 'microorganismo', tipo:'sustantivo-masculino',definicion: 'Ser vivo animal o vegetal muy pequeño'},
    // {id: 8, juego: ["DIO","ES","TA"],palabra: 'antibiótico', tipo:'sustantivo-masculino',definicion: 'Sustancia química para combatir infecciones'},
    // {id: 9, juego: ["DIO","ES","TA"],palabra: 'discurso', tipo:'sustantivo-masculino',definicion: 'exposición, escrita u oral, en la cual se manifiesta una opinión, razonamiento o deseo'},
    // {id: 10,juego: ["DIO","ES","TA"], palabra: 'Prótesis', tipo:'sustantivo-masculino',definicion: 'Brazo o pierna artificial.'},
    // {id: 11,juego: ["DIO","ES","TA"], palabra: 'Velcro', tipo:'sustantivo-masculino',definicion: 'Cinta fuerte y peluda que se pega a sí misma'},
    // {id: 12,juego: ["DIO","ES","TA"], palabra: 'Virus', tipo:'sustantivo-masculino',definicion: ' Microbios más pequeñitos que las bacterias, que causan algunas enfermedades infecciosas'},
    // {id: 13,juego: ["DIO","ES","TA"], palabra: 'Parálisis', tipo:'sustantivo-femenino',definicion: 'Debilidad de los músculos; incapacidad para mover una parte o todo el cuerpo'},
    // {id: 14,juego: ["DIO","ES","TA"], palabra: 'Plaguicidas', tipo:'sustantivo-masculino',definicion: 'Sustancias químicas que matan insectos y otras plagas'},
    // {id: 15,juego: ["DIO","ES","TA"], palabra: 'Paraplejia', tipo:'enfermedad',definicion: 'Parálisis de ambas piernas'},
    // {id: 16,juego: ["DIO","ES","TA"], palabra: 'paramédico', tipo:'adjetivo',definicion: 'Que se relaciona con la medicina sin pertenecer propiamente a esta ciencia'},
    // {id: 17,juego: ["DIO","ES","TA"], palabra: 'Fisioterapeuta', tipo:'nombre-común',definicion: 'Una persona que diseña y enseña ejercicios y actividades para personas con discapacidades físicas.'},
    // {id: 18,juego: ["DIO","ES","TA"], palabra: 'Ortopédico', tipo:'adjetivo',definicion: '— Palabra que describe aparatos, procedimientos o cirugía usados para corregir una deformidad o un impedimento físico.'},
    // {id: 19,juego: ["DIO","ES","TA"], palabra: 'arrasar', tipo:'verbo',definicion: 'Arruinar y destruir por completo un territorio, una superficie, un edificio, etc'},
    // {id: 20,juego: ["DIO","ES","TA"], palabra: 'paradigma', tipo:'nombre masculino',definicion: 'Ejemplo o modelo de algo'},
    // {id: 21,juego: ["DIO","ES","TA"], palabra: 'relieve', tipo:'nombre masculino',definicion: 'Parte que sobresale en una superficie plana.'},
]